---
title: "Distribuciones de probabilidad"
author: "Daniel"
date: "07-12-2019"
output: html_document
---

# Distribuciones de probabilidad

## Conceptos básicos

* **Expetimento aleatorio**. Experimento que efectuado en las misma condiciones puede dar lugar a resultados diferentes.
* **Suceso elemental**. Cada uno de los posibles resultados del experimento aleatorio.
* **Espacio muestral**. Conjunto $\Omega$ formado por todos los sucesos elementales del experimento aleatorio.

Ejemplo: Lanzar una moneda es un experimento aleatorio. Los sucesos elementales son: sacar cara (C) y sacar cruz (+).
El espacio muestral de este experimento es $\Omega= {\{C,+}\}$

* **Suceso**. Subconjunto del espacio muestral
* **Suceso total o seguro**. $\Omega$

**Ejemplo**: Lanzar un dado es un experimento aleatorio.
Algunos sucesos podrían ser: sacar número par ({2,4,6}), sacar mayor que 4 ({5,6}), sacar número múltiplo de 3 ({3,6})...
El suceso total de este experimento aleatorio es $\Omega = \{1,2,3,4,5,6\}$.
Un ejemplo de un suceso imposible de este experimento aleatorio es $\emptyset = {7}$ sacar 7.

**Operaciones con sucesos**. Sean $A,B\subseteq \Omega$ sucesos. Entonces,
* $A\cup B$ es el suceso unión (resultados pertencen a $A$, o a $B$, o a ambos)
* $A\cap B$ es el suceso intersección (resultados pertenecen a $A$ y $B$)
* $A^c$ es el suceso complementario (resultados que no pertenecen a $A$)
* $A-B=A\cap B^{c}$ es el suceso diferencia (resultados que pertenencen a $A$ pero no a $B$).
**Sucesos incompatibles**. Si $A\cap B=\emptyset$

**Probabilidad de un suceso**. Número entre 0 y 1 (ambos incluidos) que mide la expectativa de que se dé este suceso.

**Ejemplo**
* La probabilidad de sacar un 6 al lanzar un dado estándar no trucado es $\frac{1}{6}$.
* La probabilidad de sacar un 6 al lanzar un dado de 4 caras es 0.
* La probabilidad de sacar un 6 al lanzar un dado de 20 caras es $\frac{1}{20}$
* **Suceso vacío o imposible**. $\emptyset$

**Probabilidad**. Sea $\Omega$ el espacio muestral de un experimento aleatorio. Suponiendo que $\Omega$ es finito, una probabilidad sobre $\Omega$ es una aplicación.
$$p:\mathcal{P} (\Omega)\longrightarrow[0,1]$$
que satisface
* $0 \leq p(A) \leq 1 \forall A\in \mathcal{P} (\Omega)$
* $p(\Omega)=1$
* Si ${A_1,...,A_n}$ son sucesos incompatibles dos a dos $(A_i\cap A_j = \emptyset \forall_i \neq j)$
$$p(A_i \cup ...\cup A_n) = p(A_1)+...+p(A_n)$$

<span style="color:red">*Notación:*</span> Si $a \in \Omega$, escribiremos $p(a)$ en vez de $p({a})$

# Variables Aleatoria

**Variable Aleatoria**: Una variable aleatoria (v.a.) Sobre $\Omega$ es una aplicación

$$X:\Omega \rightarrow \mathbb{R}$$

que asigna a cada suceso elemental $\omega$ un número real $X(\omega)$

Puede entenderse como una descripción numérica de los resultados de un experimento aleatorio.

**Dominio de una variable aleatoria** $D_x$, es el conjunto de los valores que puede tomar.

## Sucesos de variables aleatorias
Una variable aleatoria puede definir sucesos, de los cuales queremos conocer la probabilidad p.
 $$p(X=a) = p(\{\omega\in \Omega |X(\omega)=a\}) $$
 $$p(X<b) = p(\{\omega\in \Omega |X(\omega)<b\}) $$
 $$p(X\leq b) = p(\{\omega\in \Omega |X(\omega)\leq b\}) $$
 $$p(a< X) = p(\{\omega\in \Omega |a <X(\omega)\}) $$
 $$p(a\leq X) = p(\{\omega\in \Omega |a\leq x(\omega)\})$$
 $$p(a\leq X \leq b) = p(\{\omega\in \Omega |a\leq X(\omega)\leq b\}) $$
 $$p(a< X < b) = p(\{\omega\in \Omega |a< X(\omega)<b\}) $$
 $$p(X\in A) = p(\{\omega\in \Omega |X(\omega)\in A\}) $$

## Función de distribución

**Función de distribución de la v.a.X.**. Es la función
$$F:\mathbb{R}\rightarrow[0,1]$$
definida por $F(x)=p(X\leq x)$
Sea $F$ una función de distribución de una v.a. $X$ y digamos
$$F(a^-) = \lim_{x-a^{-}}F(x)$$
$$p(X\leq a) =p(X \leq x)$$

## Variable aleatoria discreta

**Variable aleatoria discreta**: Una v.a. $X:\Omega \rightarrow \mathbb{R}$ es discreta cuando $D_x$ es finito o un subconjunto de $\mathbb{N}$
**Función de densidad**: Es la función $f:\mathbb{R} \rightarrow [0,1]$ definida por:
$$f(x)=p(X=x)$$
Nótese que $f(x)=0$ si $x \in D_x$. Por tanto, interpretaremos la función de densidad como la función
$$f:D_x \rightarrow [0,1]$$

## Esperanza

**Esperzana de una v.a. discreta**: Sea $f:D_x \rightarrow [0,1]$ la densidad de $X$, entonces la esperanza respecto de la densidad es la suma ponderada de los elementos de $D_x$, multiplicando cada elemento $x$ de $D_x$ por su probabilidad,
$$E(X) = \sum_{x \in D_x}x \cdot f(x)$$
Si $g:D_x \rightarrow \mathbb{R}$ es una aplicación
$$E(g(X))=\sum_{x \in D_x}g(x) \cdot f(x)$$

## Varianza

**Varianza de una v.a. discreta**. Sea $f:D_x \rightarrow [0,1]$ la densidad de $X$, entonces ña varianza respecto de la densidad es el valor esperado de la diferencia al cuadrado entre $X$ y su valor medio $E(X)$,
$$Var(X)=E((X-E(X))^{2})$$
La varianza mide como de variados son los resultados de $X$ respecto de la media.

## Desviacion típica

**Desviación típica de una v.a. discreta**: Sea $f:D_x \rightarrow[0,1]$ la densidad de $X$, entonces la desviación típica respecto de la densidad es.
$$\sigma(X) = \sqrt{Var(X)}$$
Las unidades de la varianza son las de $X$ al cuadrado. En cambio, las de la desviación típica son las mismas unidades de las de $X$.

Si $X$ es una v.a. discreta y $g: D_x \rightarrow \mathbb{R}$ una función,
$$\sigma(g(X))= \sqrt{Var((g(X))}$$

# El sesgo

Para saber que tan simetrica o asimetrica es una distribucion en torno al valor central.
Para tener una medida de que tan normal es una distribución es el sesgo, mide que tan simetrica es una distribucion.
El sesgo será un valor negativo, positivo.
El sesgo se puede calcular de forma numérica.

El sesgo se define como $\frac{\mu - med}{\sigma}$

**Coeficiente de curtosis**: Que tan alargada es la cola de una distribución.

En cuanto al sesgo de una distribución existe muchas forma de calcularlas.
* Pearson
* $\frac{\mu - med}{\sigma}$

# Las distribuciones más conocidas

Funciones para poder trabajar con variables aleatorias. Dada cualquier $va$, R nos da cuatro funciones para poder trabajar con ellas:

* **dva(x,...):** Función de densidad o de probabilidad $f(x)$ de la variable aleatoria para el valor $x$ del dominio de definición.

* **pva(x,...):** Función de una distribución $F(x)$ de la variable aleatoria para el valor $x$ del dominio de definición.

* **qva(p,...):** Cuantil $p-$ ésimo de la variable aleatoria (el valor de $x$ más pequeño tal que $F(x) \geq p$).

* **rva(n,...):** Generador de $n$ observaciones siguiendo la distribución de la variable aleatoria.


Dada cualquier $va$ aleatoria en **Python** tenemos las mismas cuatro funciones, sin que su nombre depende de la misma:

* **pmf(k,...)** o **pdf(x,...):** Función de probabilidad $f(x)$ o de densidad $f(x)$ de la variable aleatoria para los valores $k$ o $x$ del dominio.

* **cdf(x,...):** Función de distrubución de $F(x)$ de la variable aleatoria para el valor $k$ del dominio.

* **ppf(p,...):**  Cuantil $p-$ ésimo de la variable aleatoria (el valor de $x$ más pequeño tal que $F(x) \geq p$).

* **rvs(size,...):** Generador *size* observaciones siguiendo la distribución de la variable aleatoria.
